name = "GridMaps"
uuid = "889a5e0f-cea4-48d1-aea6-4a3fe9168d86"
authors = ["Nicholas Harrison"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.9"
julia = "1.10"
